version: '3.8'

services:
  devbox:
    build: .
    container_name: devbox
    tty: true  # Keeps the container running for interaction
    stdin_open: true  # Allows interactive exec
    volumes:
      - ./shared:/mnt/shared
